Aid-Pioneers/shipment-tracker

app/controllers/pallets_controller.rb, app/models/pallet.rb, app/models/user.rb, app/policies/pallet_policy.rb, app/views/pallets/_form.html.erb, app/views/pallets/new.html.erb
- adding new and show actions
- adding new view and form partial
=> Pallet create

app/controllers/shipments_controller.rb, app/policies/shipment_policy.rb, app/views/shipments/show.html.erb
- adding shipment show action and policy
- adding temporary shipment show view
=> Shipment show

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/shipments_controller.rb, app/models/user.rb, app/policies/shipment_policy.rb, app/views/devise/registrations/new.html.erb, app/views/shipments/_form.html.erb, app/views/shipments/new.html.erb
- adding shipment new / create actions and views
- changing the bootstrap primary color and border radius
=> Shipment create

app/controllers/shipments_controller.rb, app/policies/shipment_policy.rb, app/views/pages/home.html.erb, app/views/shipments/_admin_index.html.erb, app/views/shipments/_donor_index.html.erb, app/views/shipments/index.html.erb
From the home page the user is directed through same button to one of the two different index pages depending on if admin/pioneer or donor
=> home -> index pages

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/config/_fonts.scss, app/controllers/pages_controller.rb, app/models/shipment.rb, app/views/pages/donations.html.erb, app/views/shared/_shipment_card.html.erb, config/routes.rb
- adding donor page at `/donations`
- still missing the map
- currently gets all the shipments because we have no proper policy_scope for donors
- changing bootstrap variables according to figma
=> adding donor page without map

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_login.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
=> login and signup style

app/controllers/shipments_controller.rb, app/models/shipment.rb, app/views/shipments/_form.html.erb, db/migrate/20220602142626_add_status_to_shipment.rb, db/schema.rb, db/seeds.rb
- adding status column to shipments (default: 0 / in_preparation)
- adding enum in shipment model
- adding select in shipment form
- adding seed
=> adding status to shipments

app/controllers/pages_controller.rb, app/controllers/scans_controller.rb, app/controllers/shipments_controller.rb, app/models/scan.rb, app/views/pages/donations.html.erb, app/views/pages/success.html.erb, app/views/scans/new.html.erb, app/views/shared/_shipment_card.html.erb, app/views/shipments/show.html.erb, config/routes.rb, db/seeds.rb
Perfect PR to review on a monday morning. 😄
=> Various improvements

app/assets/stylesheets/pages/_admin-index.scss, app/controllers/shipments_controller.rb, app/javascript/controllers/update_shipments_controller.js, app/models/shipment.rb, app/views/shared/_sidenav.html.erb, app/views/shipments/_admin_index.html.erb, app/views/shipments/_shipment_card_admin_index.html.erb
- added buttons according to shipment status
- made partial for shipment card
=> Ngo index 2

app/views/shipments/_admin_index.html.erb
- fixing the shipment index rows
- when the screen size is too small the map with be under the shipment list
=> fixing shipment index rows

app/controllers/pallets_controller.rb, app/models/pallet.rb, app/views/pallets/_form.html.erb, app/views/pallets/edit.html.erb, app/views/shipments/show.html.erb
- fixing pallet paths and forms
- adding margins at some places
=> various fixes

app/assets/stylesheets/pages/_admin-index.scss, app/views/shipments/_admin_index.html.erb
Hi all, can you please review.
@finnstue design is ok?
=> clickable button + layout

app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
=> unstuck footer + added margin on cards

app/assets/stylesheets/pages/_admin-index.scss, app/views/shipments/_admin_index.html.erb, app/views/shipments/_shipment_card_admin_index.html.erb
Here is a first push for review.
Just didn't manage to make the text "Track on map" bigger. 
I can check that after review.
=> update layout index

app/assets/stylesheets/components/_sidenav.scss, app/views/layouts/application.html.erb, app/views/shared/_sidenav.html.erb
- readding sidenav on every page but home
- adding sidenav toggle button
- sidenav is collapsed by default
=> add sidebar collapsing and toggle button

README.md, config/database.yml
=> Feature/add instructions for docker (Fixes #79)

Gemfile.lock
It looks like some versions aren't pinned for my platform, so pushing these up 👍
=> Gemfile lock updates.

app/controllers/shipments_controller.rb, app/javascript/controllers/mapbox_show_pallets_controller.js, app/views/shipments/show.html.erb
The feature has an error. The width of the map that is supposed to show the pallets is too small.
=> tab to switch between the location of a shipment and the location of this shipments pallets

app/controllers/projects_controller.rb, app/policies/project_policy.rb, app/views/pages/home.html.erb, app/views/projects/new.html.erb
https://github.com/Aid-Pioneers/shipment-tracker/issues/67
Added:
- project policy that allows only admins to create project
- controller for creating projects
- form for creating projects
=> Issue 67: Enable admins to add projects

app.json, app/controllers/scans_controller.rb
A mishmash of following steps from [here](https://devcenter.heroku.com/articles/heroku-ci-in-dyno-databases) and then looking into what an app.json actually is [here](https://devcenter.heroku.com/articles/app-json-schema).
Fixes #71
=> Add an app.json to spin up a postgres DB for the tests.

app/views/shipments/show.html.erb
Currently, it opens in the same tab, and then the backwards/forwards navigations of the browser appear to entirely break...
https://stackoverflow.com/a/17711167
=> Force QR code to open in new window/tab.

Gemfile.lock, app/models/pallet.rb, app/views/shipments/show.html.erb, db/migrate/20230322185228_add_is_complete_to_pallet.rb, db/schema.rb
There is still some work to do (see the issue for details) but the commits are split out by change.
Fixes #94
=> Feat 94/add mark as complete

app/controllers/pallets_controller.rb, app/models/pallet.rb, app/views/pallets/_form.html.erb, app/views/shipments/show.html.erb
There was an issue that pallets were not being created, this should fix it.
=> Fix: set is_complete to false by default

app/controllers/shipments_controller.rb, app/models/shipment.rb, app/views/shipments/_shipment_card_admin_index.html.erb, app/views/shipments/show.html.erb
=> Add % markers to shipment view.

app/models/shipment.rb, app/views/shipments/show.html.erb
Without this change, the app still runs locally, unsure what the problem is here, but maybe this will help fix it.
=> Allow for is_complete to be empty.
